version: 1
db_path: ~/.music_player.db
base_folder: ~/Music
average_track_duration_seconds: 245
crossfade_seconds: 3.5
ui_fade_seconds: 0.25
silence_threshold_db: -60.0
autoqueue_prepopulate_count: 5
supported_extensions:
- .mp3
- .flac
- .ogg
- .m4a
- .wav
- .aac
- .mp2
compressor:
  rms_peak: 0.0
  attack_time: 1.5
  release_time: 32.5
  threshold_level: -20.0
  ratio: 4.0
  knee_radius: 2.0
  makeup_gain: 0.0
daily_folder: daily
logging:
  level: INFO
  file: ~/.cache/pegasus-player/pegasus_player.log
timeslots:
- name: morning
  start: 07:00
  end: '13:00'
  folders:
  - morning
  - shared
  each_iteration_folder: every_morning
- name: afternoon-1
  start: '13:00'
  end: '14:00'
  folders:
  - afternoon
  - shared
  each_iteration_folder: every_afternoon
- name: naptime
  start: '14:00'
  end: '16:00'
  folders:
  - morning
  - shared
  each_iteration_folder: NOT_IN_USE
- name: afternoon-2
  start: '16:00'
  end: 03:00
  folders:
  - afternoon
  - shared
  each_iteration_folder: every_afternoon
- name: night
  start: 03:00
  end: 07:00
  folders:
  - NOT_IN_USE
  each_iteration_folder: NOT_IN_USE
